apiVersion: v1
kind: Namespace
metadata:
  name: iwiick-proj-staging
  labels:
    environment-id: env_9fa26826-bf5e-4395-a174-cc05d8beab0b
    project-id: project_3b037a6f-2614-4ea4-b15e-9dc41a5bfa60
    project-name: iwiick-proj
    environment-name: staging
    organization-id: org_1f902008-1f74-4040-8d55-a285aa0d7507
