apiVersion: v1
kind: Namespace
metadata:
  name: iwick-proj-prod
  labels:
    environment-id: env_5516049c-1ab8-4b01-8143-cf76bbc6c910
    project-id: project_ac1e5bc9-dd50-4c3f-8a21-89e0a6e64063
    project-name: iwick-proj
    environment-name: prod
    organization-id: org_51f9f009-7930-486b-a047-1ce7d6ef103b
