apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 5001
          targetPort: 5001
          protocol: TCP
          apiSpec:
            gitPath: swagger-specification.yml
      healthChecks: []
      name: coffee-user-service-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/coffee-user-service
      credentialId: credential_138659b9-05db-444a-a093-da7cf80f00de
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: coffee-user-service
    version: v1.0.0
    applicationId: app_b5515b8a-b109-424e-ab36-8eb09d997f9d
    projectId: project_1f4dfeae-6b8b-4241-a59e-5e885be21a8d
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    environmentId: env_8598c207-4bd1-4f88-a825-898c80b563e2
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: coffee-user-service
  serviceType: ClusterIP
  version: v1.0.0
  namespace: swagger-apps-prod
