name: My Test Workflow (Heshan) (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
env: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
