name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build With Docker
        run: >-
          docker images && docker build -t pipeline-svc:${{ github.sha }} . &&
          docker images
