name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
env:
  IMAGE_NAME: test-service-img
  DOCKER_FILE_PATH: /src
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
