name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.TESTSERVICE2_ENV_4F51CAF0C8654A53929B37F388F62ACD_APP_7D7EEA94AEC143378BF001E10B98622C_CICD}}
  REPOSITORY_NAME: iwiick
  RANDOM_ENV_VALUE: HAHAHAHAHA
  TEST_ENV_WITH_SECRET_VAL: ${{secrets.DOCKER_IMAGE_NAME}}
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Decoding Secrets'
        run: >-
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r
          'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV && env
      - name: 'Run :: Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.roleARN }}
          role-session-name: skyu-pipeline-assume-role-session
          aws-region: ${{ env.region }}
      - name: 'Run :: Login to Amazon ECR'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: 'Run :: Deploy and Notify Resource Service'
        run: >-
          echo "imageRegistryURL :: ${{ steps.login-ecr.outputs.registry }}
           appVersionId :: ${{ env.DEPLOYMENT_APP_VERSION_ID }}
            tag :: ${{ env.IMAGE_NAME_TO_PUSH }}
           containerName :: ${{ env.DEPLOYMENT_CONTAINER_NAME }}
           Access Token :: ${{env.SERVICE_ACC_ACCESS_TOKEN}}
            Commit Hash :: ${{ github.event.after }}
           Commit Avatar :: https://github.com/${{ github.event.head_commit.author.name }}.png
           Commit Time :: ${{ github.event.head_commit.timestamp }}
           Commit Message :: ${{ github.event.head_commit.message }}
           Commit Author :: ${{ github.event.head_commit.author.name }}
          " && curl -X GET "https://api.dev.skyu.io/secret-service/health" 
          --insecure
      - name: My Custom Step
        run: >-
          echo " Pipeline service works yall!.
          $\{\{secrets.DOCKER_IMAGE_NAME\}\} and $\{\{env.RANDOM_ENV_VALUE\}\}"
