name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
env:
  DOCKER_FILE_NAME: Dockerfile
  IMAGE_NAME: test-service-img
  SCAN_SEVERITY: CRITICAL
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
