name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
env:
  IMAGE_NAME: ${{secrets.DOCKER_IMAGE_NAME}}
  DOCKER_FILE_NAME: Dockerfile
  RANDOM_ENV_VALUE: HAHAHAHAHA
  TEST_ENV_WITH_SECRET_VAL: ${{secrets.DOCKER_IMAGE_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Build With Docker'
        run: >-
          docker images && docker build -t ${{ env.IMAGE_NAME }} -f
          ${{env.DOCKER_FILE_NAME}} .${{env.DOCKER_FILE_PATH}} && docker images
      - name: 'Run :: Decoding Secrets'
        id: skyu_parse_secrets
        run: >-
          MY_SECRET_BASE64=${{ env.MY_SECRET }} && MY_SECRET_JSON=$(echo
          $MY_SECRET_BASE64 | base64 --decode) && echo Decoded JSON:
          $MY_SECRET_JSON && echo ::set-output
          name=MY_SECRET_JSON::$MY_SECRET_JSON
      - name: My Custom Step
        run: >-
          echo " Pipeline service works yall!.
          $\{\{secrets.DOCKER_IMAGE_NAME\}\} and $\{\{env.RANDOM_ENV_VALUE\}\}"
