name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
env:
  IMAGE_NAME: test-image
  DOCKER_FILE_NAME: Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build With Docker
        run: >-
          docker images && docker build -t ${{ env.IMAGE_NAME }} -f
          ${{env.DOCKER_FILE_NAME}} .${{env.DOCKER_FILE_PATH}} && docker images
