name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.TESTSERVICE2_ENV_4F51CAF0C8654A53929B37F388F62ACD_APP_7D7EEA94AEC143378BF001E10B98622C_CICD}}
  REPOSITORY_NAME: iwiick
  RANDOM_ENV_VALUE: HAHAHAHAHA
  TEST_ENV_WITH_SECRET_VAL: ${{secrets.DOCKER_IMAGE_NAME}}
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Decoding Secrets'
        run: >-
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r
          'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV && env
      - name: 'Run :: Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.roleARN }}
          role-session-name: skyu-pipeline-assume-role-session
          aws-region: ${{ env.region }}
      - name: 'Run :: Login to Amazon ECR'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: 'Run :: Deploy and Notify Resource Service'
        run: >-
          curl --insecure -XPATCH -H 'Authorization:
          ${{env.SERVICE_ACC_ACCESS_TOKEN}}' -H "Content-type: application/json"
          -d '{"imageRegistryURL":"${{ steps.login-ecr.outputs.registry
          }}","appVersionId":"${{ env.DEPLOYMENT_APP_VERSION_ID }}","tag":"${{
          env.IMAGE_NAME_TO_PUSH }}","containerName":"${{
          env.DEPLOYMENT_CONTAINER_NAME }}","commitDetails":{"commitHash":"${{
          github.event.after }}","commitAvatar":"https://github.com/${{
          github.event.head_commit.author.name }}.png","commitTime":"${{
          github.event.head_commit.timestamp }}","commitMessage":"${{
          github.event.head_commit.message }}","commitUser":"${{
          github.event.head_commit.author.name }}"}}'
          'https://api.dev.skyu.io/resource-service/applications/deploy'
      - name: My Custom Step
        run: >-
          echo " Pipeline service works yall!.
          $\{\{secrets.DOCKER_IMAGE_NAME\}\} and $\{\{env.RANDOM_ENV_VALUE\}\}"
