name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.TESTSERVICE2_ENV_D257AF4E9409415F974CFDD70A2A25DF_APP_0666FAC591E24B38A5C3176884514379_CICD}}
  IMAGE_NAME: iwiick-test-image:latest
  IMAGE_NAME_TO_PUSH: iwiick-test-image.latest
  DOCKER_FILE_NAME: sample.Dockerfile
  DOCKER_FILE_PATH: /src
  SCAN_SEVERITY: HIGH
  REPOSITORY_NAME: iwiick
  RANDOM_ENV_VALUE: HAHAHAHAHA
  TEST_ENV_WITH_SECRET_VAL: ${{secrets.DOCKER_IMAGE_NAME}}
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Decoding Secrets'
        run: >-
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r
          'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo
          "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
      - name: 'Run :: Build With Docker'
        run: >-
          docker images && docker build -t ${{ env.IMAGE_NAME }} -f
          ${{env.DOCKER_FILE_NAME}} .${{env.DOCKER_FILE_PATH}} && docker images
      - name: 'Run :: Trivy vulnerability scanner'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: ${{env.SCAN_SEVERITY}}
      - name: 'Run :: Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.roleARN }}
          role-session-name: skyu-pipeline-assume-role-session
          aws-region: ${{ env.region }}
      - name: 'Run :: Login to Amazon ECR'
        id: skyu-login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: 'Run :: Create Repository'
        run: >-
          aws ecr create-repository --repository-name ${{ env.REPOSITORY_NAME }}
          || true
      - name: 'Run :: Build, tag, and push image to Amazon ECR'
        run: >-
          docker build -t ${{ steps.skyu-login-ecr.outputs.registry
          }}/${{env.REPOSITORY_NAME}}:${{ env.IMAGE_NAME_TO_PUSH }} . && docker
          push ${{ steps.skyu-login-ecr.outputs.registry
          }}/${{env.REPOSITORY_NAME}}:${{ env.IMAGE_NAME_TO_PUSH }}
      - name: 'Run :: Deploy and Notify Resource Service'
        run: >-
          curl -d "imageRegistryURL=${{ steps.skyu-login-ecr.outputs.registry
          }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{
          env.IMAGE_NAME_TO_PUSH }}&containerName=${{
          env.DEPLOYMENT_CONTAINER_NAME }}&commitDetails[commitHash]=${{
          github.event.after
          }}&commitDetails[commitAvatar]=https://github.com/${{
          github.event.head_commit.author.name
          }}.png&commitDetails[commitTime]=${{
          github.event.head_commit.timestamp
          }}&commitDetails[commitMessage]=\"${{ github.event.head_commit.message
          }}\"&commitDetails[commitUser]=${{
          github.event.head_commit.author.name }}" -X PATCH -H 'Authorization:
          ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{
          env.DEPLOYMENT_ORGANIZATION_ID }}' -H 'x-project-id: ${{
          env.DEPLOYMENT_PROJECT_ID }}' -H 'x-environment-id: ${{
          env.DEPLOYMENT_ENVIRONMENT_ID }}' -H 'x-application-id: ${{
          env.DEPLOYMENT_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type:
          application/x-www-form-urlencoded'
          'https://api.dev.skyu.io/resource-service/applications/deploy'
      - name: 'Run :: My Custom Step'
        run: >-
          echo " Pipeline service works yall!.
          $\{\{secrets.DOCKER_IMAGE_NAME\}\} and $\{\{env.RANDOM_ENV_VALUE\}\}"
