name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
env:
  RANDOM_ENV_VALUE: HAHAHAHAHA
  TEST_ENV_WITH_SECRET_VAL: ${{secrets.DOCKER_IMAGE_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: My Custom Step
        run: >-
          echo " Pipeline service works yall!.
          $\{\{secrets.DOCKER_IMAGE_NAME\}\} and $\{\{env.RANDOM_ENV_VALUE\}\}"
