name: container-dev_app_e6745e6_env_43e64b6 Pipeline (Skyu Generated)
'on':
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - .github/workflows/**
      - .trivyignore
      - Readme.md
      - README.md
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_a6e11b84-3f93-4da5-8912-84f791e1f10a
env:
  ENCODED_PIPELINE_SECRET: ${{secrets.TESTSERVICE2_CONTAINERDEV_APP_E6745E6_ENV_43E64B6}}
  COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
  BRANCH_NAME: >-
    ${{github.event.client_payload.branchName || github.event.branch ||
    github.ref_name}}
  DEPLOY_STEP_SHOULD_DEPLOY: 'true'
jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Test Docker compose'
        run: docker compose --version
  
            
