name: >-
  container-dev_env_c98a73f8-92be-4110-83ea-3ce0228e4339_app_65a6570c-c6d3-4c01-a4c5-bb12461eb89e
  Pipeline (Skyu Generated) (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_e9ed9b68-98e1-4c1c-9346-1d0ff925bce5
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.TESTSERVICE2_ENV_C98A73F892BE411083EA3CE0228E4339_APP_65A6570CC6D34C01A4C5BB12461EB89E_CONTAINERDEV_ENV_C98A73F892BE411083EA3CE0228E4339_APP_65A6570CC6D34C01A4C5BB12461EB89E}}
  CHECK_IMAGE_EXISTENCE: 'true'
  IMG_URL: '272133924862.dkr.ecr.us-east-1.amazonaws.com/iwiick'
  # Support Http trigger
  IMG_TAG: ${{ github.sha }}
  DOCKER_FILE_NAME: Dockerfile
  REPOSITORY_NAME: iwiick
  SCAN_SEVERITY: CRITICAL
  TRIVY_SCAN_EXIT_CODE: '1'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Decoding Secrets'
        run: >-
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r
          'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo
          "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
      - name: 'Run :: Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.roleARN }}
          role-session-name: skyu-pipeline-assume-role-session
          aws-region: ${{ env.region }}
      - name: 'Run :: Login to Amazon ECR'
        id: skyu-login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: 'Run :: Check if image already exists in AWS Ecr'
        id: check-image-exists-in-aws-ecr
        run: |2-
            if docker pull ${{ env.IMG_URL }}:${{env.IMG_TAG}} >/dev/null 2>&1; then
              echo "Image exists in registry."
              echo "IMAGE_EXISTS_IN_ECR=true" >> $GITHUB_ENV
            else
              echo "Image does not exist in registry."
              echo "IMAGE_EXISTS_IN_ECR=false" >> $GITHUB_ENV
            fi
      - name: 'Run :: Build With Docker'
        run: >-
          docker build -t ${{ env.IMG_URL }}:${{env.IMG_TAG}} -f
          ${{env.DOCKER_FILE_NAME}} .${{env.DOCKER_FILE_PATH}}
        if: >-
          ${{ env.IMAGE_EXISTS_IN_ECR }} == 'false' && ${{
          env.CHECK_IMAGE_EXISTENCE }} == 'true' || ${{
          env.CHECK_IMAGE_EXISTENCE }} == 'false'
      - name: 'Run :: Create Repository'
        run: >-
          aws ecr create-repository --repository-name ${{ env.REPOSITORY_NAME }}
          || true
        if: >-
          ${{ env.IMAGE_EXISTS_IN_ECR }} == 'false' && ${{
          env.CHECK_IMAGE_EXISTENCE }} == 'true' || ${{
          env.CHECK_IMAGE_EXISTENCE }} == 'false'
      - name: 'Run :: Build, tag, and push image to Amazon ECR'
        run: >-
          docker push ${{ env.IMG_URL }}:${{env.IMG_TAG}}
        if: >-
          ${{ env.IMAGE_EXISTS_IN_ECR }} == 'false' && ${{
          env.CHECK_IMAGE_EXISTENCE }} == 'true' || ${{
          env.CHECK_IMAGE_EXISTENCE }} == 'false'
      - name: 'Run :: Trivy vulnerability scanner'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMG_URL }}:${{env.IMG_TAG}}
          format: table
          output: trivy-results.json
          exit-code: ${{env.TRIVY_SCAN_EXIT_CODE}}
          ignore-unfixed: true
          vuln-type: os,library
          severity: ${{env.SCAN_SEVERITY}}
        if: >-
          ${{ env.IMAGE_EXISTS_IN_ECR }} == 'false' && ${{
          env.CHECK_IMAGE_EXISTENCE }} == 'true' || ${{
          env.CHECK_IMAGE_EXISTENCE }} == 'false'
      - name: 'Run :: Deploy and Notify Resource Service'
        run: |2-

              response=$(curl -d "imageRegistryURL=${{ steps.skyu-login-ecr.outputs.registry }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.IMG_TAG }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&commitDetails[commitHash]=${{ github.event.after }}&commitDetails[commitAvatar]=https://github.com/${{ github.event.head_commit.author.name }}.png&commitDetails[commitTime]=${{ github.event.head_commit.timestamp }}&commitDetails[commitMessage]=\"${{ github.event.head_commit.message }}\"&commitDetails[commitUser]=${{ github.event.head_commit.author.name }}" -X PATCH -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.DEPLOYMENT_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.DEPLOYMENT_PROJECT_ID }}' -H 'x-environment-id: ${{ env.DEPLOYMENT_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.DEPLOYMENT_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded' 'https://api.dev.skyu.io/resource-service/applications/deploy')

              status_code=$?

              if [ $status_code -eq 0 ]; then
                if echo "$response" | grep -q '"message":"Unauthorized"'; then
                  echo "FAILED :: Unauthorized access."
                  exit 1
                else
                  echo "SUCCESS :: Response: $response"
                fi
              else
                echo "Failed to deploy. HTTP status code: $status_code"
                exit 1
              fi
            
