name: >-
  container-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_91eb6f12-25e2-41b6-9613-6b2cd45a67fe
  Pipeline (Skyu Generated)
'on':
  push:
    branches:
      - master
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_d37c9985-1098-417e-b33d-46e182a1ab27
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.TESTSERVICE2_ENV_2046883CF8A34774AE10510D8AB9865A_APP_91EB6F1225E241B696136B2CD45A67FE_CONTAINERDEV_ENV_2046883CF8A34774AE10510D8AB9865A_APP_91EB6F1225E241B696136B2CD45A67FE}}
  IMAGE_TAG: ${{github.event.client_payload.commitId || github.sha}}
  IMAGE_NAME: ghcr.io/${{github.repository_owner}}/iwiick
  DOCKER_FILE_PATH: Dockerfile
  DOCKER_BUILD_CONTEXT: .
  SCAN_SEVERITY: CRITICAL
  TRIVY_SCAN_EXIT_CODE: '1'
  TRIVY_RESULT_FORMAT: json
  REPOSITORY_NAME: iwiick
  DEPLOY_STEP_SHOULD_DEPLOY: 'true'
jobs: {}
