name: >-
  pr-default_env_c98a73f8-92be-4110-83ea-3ce0228e4339_app_65a6570c-c6d3-4c01-a4c5-bb12461eb89e
  Pipeline (Skyu Generated) (Skyu Generated)
'on':
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_d934fd06-583f-4971-987a-1cedd515d4f2
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.TESTSERVICE2_ENV_C98A73F892BE411083EA3CE0228E4339_APP_65A6570CC6D34C01A4C5BB12461EB89E_PRDEFAULT_ENV_C98A73F892BE411083EA3CE0228E4339_APP_65A6570CC6D34C01A4C5BB12461EB89E}}
  IMAGE_NAME: skyu-gen-img
  IMAGE_TAG: ${{github.sha}}
  DOCKER_FILE_NAME: Dockerfile
  SCAN_SEVERITY: HIGH
  TRIVY_SCAN_EXIT_CODE: '0'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Decoding Secrets'
        run: >-
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r
          'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo
          "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
      - name: 'Run :: Build With Docker'
        run: >-
          docker build -t ${{ env.registryURL }}/${{env.REPOSITORY_NAME}}:${{
          env.IMAGE_TAG }} -f ${{env.DOCKER_FILE_NAME}}
          .${{env.DOCKER_FILE_PATH}}
      - name: 'Run :: Trivy vulnerability scanner'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.registryURL }}/${{env.REPOSITORY_NAME}}:${{ env.IMAGE_TAG }}
          format: table
          output: trivy-results.json
          exit-code: ${{env.TRIVY_SCAN_EXIT_CODE}}
          ignore-unfixed: true
          vuln-type: os,library
          severity: ${{env.SCAN_SEVERITY}}
      - name: 'Run :: Comment on PR with Trivy Summary'
        uses: actions/github-script@v6
        with:
          script: |2-

                  const fs = require('fs');
                  const trivySummary = fs.readFileSync('trivy-results.json', 'utf-8');

                  github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: 'Trivy ${{env.SCAN_SEVERITY}} Vulnerability Scan Results\n```\n' + trivySummary + '\n```',
                  });
                  
