name: trigger test
'on':
  repository_dispatch:
    types: do-something
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo " Starting GitHub Action!"
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: Do Something
        run: echo Doing Something...
